on: [pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Comment on PR with jest coverage
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - name: Comment on PR with jest coverage
        uses: emilioSp/hello-world-javascript-action@v1.5.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}